### ISSUE TITLE
可以在控制台设置管理员，但在群里对.mrsr没有反应

### ISSUE THREAD

**Issue by SnowMoonSS** [yc0037/MiraiReplier#2]
已安装的插件
|插件|版本|
|---|---|
|[Mirai Console Loader](https://github.com/iTXTech/mirai-console-loader)|1.0.5|
|||
|[mirai-core-all](https://github.com/mamoe/mirai)|2.5.0|
|[mirai-console](https://github.com/mamoe/mirai-console)|2.5.0|
|mirai-console-terminal|2.5.0|
|||
|[chat-command](https://github.com/project-mirai/chat-command)|0.5.1|
|[mirai-console-lolicon](https://github.com/Samarium150/mirai-console-lolicon)|3.1.0|
|[MiraiSongPlugin](https://github.com/khjxiaogu/MiraiSongPlugin)|2.0-0.2.2|
|[onebot-mirai](https://github.com/yyuueexxiinngg/onebot-kotlin)|0.3.4|
|[RosemoeBotPlugin](https://github.com/Rosemoe/BotPlugin)|2.3|

情况如题，在群里使用.mrsr，控制台没有任何提示，bot也没有任何反应

**Comment by yc0037** [comment]
目前确实不会响应群里的 .mrsr 消息，后续版本也许会支持

**Comment by SnowMoonSS** [comment]
> 目前确实不会响应群里的 .mrsr 消息，后续版本也许会支持

啊这……原来本就不支持……

哦哦，我懂了，关键词设置是只有私聊能设置，但设置好的关键词在群里生效
